"""initial_schema

Revision ID: 2a6b0ff3036f
Revises: 
Create Date: 2026-06-14 00:49:48.976640
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '2a6b0ff3036f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skus',
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('packaging_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('overhead_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_table('standard_components',
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('assemblies',
    sa.Column('assembly_id', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('assembly_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.sku_id'], ),
    sa.PrimaryKeyConstraint('assembly_id')
    )
    op.create_index(op.f('ix_assemblies_sku_id'), 'assemblies', ['sku_id'], unique=False)
    op.create_table('cost_versions',
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('parent_version_id', sa.String(length=64), nullable=True),
    sa.Column('version_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['cost_versions.version_id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.sku_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_cost_versions_sku_id'), 'cost_versions', ['sku_id'], unique=False)
    op.create_table('quotations',
    sa.Column('quotation_id', sa.String(length=64), nullable=False),
    sa.Column('quotation_no', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('risk_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('target_margin', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.sku_id'], ),
    sa.PrimaryKeyConstraint('quotation_id'),
    sa.UniqueConstraint('quotation_no')
    )
    op.create_index(op.f('ix_quotations_sku_id'), 'quotations', ['sku_id'], unique=False)
    op.create_table('cost_snapshots',
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('process_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('mold_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('assembly_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('standard_component_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('outsourced_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('packaging_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('overhead_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['cost_versions.version_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('parts',
    sa.Column('part_id', sa.String(length=64), nullable=False),
    sa.Column('assembly_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('standard_component_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.assembly_id'], ),
    sa.ForeignKeyConstraint(['standard_component_id'], ['standard_components.component_id'], ),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_index(op.f('ix_parts_assembly_id'), 'parts', ['assembly_id'], unique=False)
    op.create_table('molds',
    sa.Column('mold_id', sa.String(length=64), nullable=False),
    sa.Column('part_id', sa.String(length=64), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cavity', sa.Integer(), nullable=False),
    sa.Column('planned_output', sa.Integer(), nullable=False),
    sa.Column('actual_output', sa.Integer(), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('mold_id')
    )
    op.create_index(op.f('ix_molds_part_id'), 'molds', ['part_id'], unique=False)
    op.create_table('outsourced_parts',
    sa.Column('outsourced_id', sa.String(length=64), nullable=False),
    sa.Column('part_id', sa.String(length=64), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('process_type', sa.String(length=64), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('yield_assumption', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('lead_time', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('outsourced_id')
    )
    op.create_index(op.f('ix_outsourced_parts_part_id'), 'outsourced_parts', ['part_id'], unique=False)
    op.create_table('production_records',
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('part_id', sa.String(length=64), nullable=False),
    sa.Column('process_type', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('good_qty', sa.Integer(), nullable=False),
    sa.Column('cycle_time_actual', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('scrap_qty', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_production_records_part_id'), 'production_records', ['part_id'], unique=False)
    op.create_table('routings',
    sa.Column('routing_id', sa.String(length=64), nullable=False),
    sa.Column('part_id', sa.String(length=64), nullable=False),
    sa.Column('process_type', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('machine', sa.String(length=100), nullable=False),
    sa.Column('cycle_time', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('labor_count', sa.Integer(), nullable=False),
    sa.Column('machine_rate_per_hour', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('labor_rate_per_hour', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('yield_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('routing_id')
    )
    op.create_index(op.f('ix_routings_part_id'), 'routings', ['part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routings_part_id'), table_name='routings')
    op.drop_table('routings')
    op.drop_index(op.f('ix_production_records_part_id'), table_name='production_records')
    op.drop_table('production_records')
    op.drop_index(op.f('ix_outsourced_parts_part_id'), table_name='outsourced_parts')
    op.drop_table('outsourced_parts')
    op.drop_index(op.f('ix_molds_part_id'), table_name='molds')
    op.drop_table('molds')
    op.drop_index(op.f('ix_parts_assembly_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_table('cost_snapshots')
    op.drop_index(op.f('ix_quotations_sku_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_cost_versions_sku_id'), table_name='cost_versions')
    op.drop_table('cost_versions')
    op.drop_index(op.f('ix_assemblies_sku_id'), table_name='assemblies')
    op.drop_table('assemblies')
    op.drop_table('standard_components')
    op.drop_table('skus')
    # ### end Alembic commands ###
