"""add_cost_data_approval_workflow

Revision ID: bed61484138c
Revises: 2a6b0ff3036f
Create Date: 2026-06-14 07:36:52.903028
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'bed61484138c'
down_revision: Union[str, None] = '2a6b0ff3036f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_data_submissions',
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('source_mode', sa.String(length=32), nullable=False),
    sa.Column('submitted_by', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('applied_record_id', sa.String(length=64), nullable=True),
    sa.Column('applied_version_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['applied_record_id'], ['production_records.record_id'], ),
    sa.ForeignKeyConstraint(['applied_version_id'], ['cost_versions.version_id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.sku_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_cost_data_submissions_sku_id'), 'cost_data_submissions', ['sku_id'], unique=False)
    op.create_index(op.f('ix_cost_data_submissions_status'), 'cost_data_submissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_data_submissions_status'), table_name='cost_data_submissions')
    op.drop_index(op.f('ix_cost_data_submissions_sku_id'), table_name='cost_data_submissions')
    op.drop_table('cost_data_submissions')
    # ### end Alembic commands ###
